<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.9.10</Version>
    <AssemblyName>OmniWheelPC</AssemblyName>
    <RootNamespace>OmniWheelPC</RootNamespace>
    <SelfContained>false</SelfContained>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="steering_wheel.png" />
  </ItemGroup>

</Project>